// Generated by scripts/generate_creative_catalog.py. Do not edit.
package com.androidagent.client.creative.styles

import androidx.compose.runtime.Composable

@Composable
internal fun CreativeStyleContent(style: CreativeStyleSpec, pattern: CreativePattern, interactive: Boolean) {
    when (pattern.id) {
        "archive" -> StyleArchive(style, pattern, interactive)
        "flora" -> StyleFlora(style, pattern, interactive)
        "transit" -> StyleTransit(style, pattern, interactive)
        "focus" -> StyleFocus(style, pattern, interactive)
        "orbit" -> StyleOrbit(style, pattern, interactive)
        "spectrum" -> StyleSpectrum(style, pattern, interactive)
        "terrain" -> StyleTerrain(style, pattern, interactive)
        "kinetic" -> StyleKinetic(style, pattern, interactive)
        "fluidknob" -> StyleFluidknob(style, pattern, interactive)
        "radialtool" -> StyleRadialtool(style, pattern, interactive)
        "fielddots" -> StyleFielddots(style, pattern, interactive)
        "morphstamp" -> StyleMorphstamp(style, pattern, interactive)
        "foiltilt" -> StyleFoiltilt(style, pattern, interactive)
        "depthstack" -> StyleDepthstack(style, pattern, interactive)
        "flapcounter" -> StyleFlapcounter(style, pattern, interactive)
        "liquidswipe" -> StyleLiquidswipe(style, pattern, interactive)
        "elasticnav" -> StyleElasticnav(style, pattern, interactive)
        "paperfold" -> StylePaperfold(style, pattern, interactive)
        "scratchmap" -> StyleScratchmap(style, pattern, interactive)
        "flowtext" -> StyleFlowtext(style, pattern, interactive)
        "arcchart" -> StyleArcchart(style, pattern, interactive)
        "typesort" -> StyleTypesort(style, pattern, interactive)
        "depthwheel" -> StyleDepthwheel(style, pattern, interactive)
        else -> error("Unknown creative layout: ${pattern.id}")
    }
}
