const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const { randomUUID, createHash } = require("node:crypto");

module.exports = async function communityFlow({page,base,data,output}) {
  const [a,b]=JSON.parse(await fs.readFile(path.join(data,"test-authors.json"),"utf8"));
  async function request(account,method,route,body,expected=200,raw=false) {
    const response=await fetch(base+route,{method,headers:{Authorization:`Bearer ${account.token}`,...(body?{"Content-Type":raw?"application/octet-stream":"application/json"}:{})},body:body?(raw?body:JSON.stringify(body)):undefined});
    assert.equal(response.status,expected,await response.clone().text());return response.json();
  }
  function action(item){const revision=item.revisions.find(r=>r.id===item.revision_id);return {expected_version:item.row_version,revision_id:revision.id,content_hash:revision.content_hash};}
  const bytes=await fs.readFile(path.join(data,"cover.png"));
  const upload=await request(a,"POST","/api/me/creative/uploads",{client_id:randomUUID(),sha256:createHash("sha256").update(bytes).digest("hex"),size:bytes.length},201);
  const complete=await request(a,"PUT",`/api/me/creative/uploads/${upload.id}/content`,bytes,200,true);
  let item=await request(a,"POST","/api/me/creative/items",{client_id:randomUUID(),content:{title:"用户上传的导航组件",summary:"跨账号发布流程",category_id:"navigation",license:"MIT",cover_asset_id:complete.asset_id,files:[{path:"Navigation.kt",content:'@Composable fun Navigation() { Text("用户原创 v1") }'}]}},201);
  const route=`/api/me/creative/items/${item.id}`,publicRoute=`/api/creative/items/${item.id}`;
  await request(b,"GET",route,null,404);
  await request(b,"GET",publicRoute,null,404);
  item=await request(a,"POST",route+"/submit",{...action(item),sharing_confirmed:true});
  await page.getByRole("button",{name:"刷新",exact:true}).click();
  await page.getByRole("button",{name:"查看稿件与差异",exact:true}).click();
  await page.getByRole("img",{name:"投稿封面",exact:true}).waitFor();
  assert.equal(await page.locator(".review-columns img").count(),0);
  await page.getByLabel("作者可见的审核意见",{exact:true}).fill("初审通过");
  await page.getByLabel("管理员内部备注（不向作者公开）",{exact:true}).fill("INTERNAL-REVIEW-ONLY");
  await page.screenshot({path:path.join(output,"community-review.png")});
  await page.getByRole("button",{name:"批准并发布",exact:true}).click();
  await page.locator("dialog[open]").waitFor({state:"hidden"});
  const published=await request(b,"GET",publicRoute);
  assert.equal(published.origin,"community");assert.equal(published.author_name,"创作者 0");assert.equal(published.title,"用户上传的导航组件");
  let own=await request(a,"GET",route);
  assert(!JSON.stringify(own).includes("INTERNAL-REVIEW-ONLY"));
  const notices=await request(a,"GET","/api/me/creative/notifications");
  assert(notices.items.some(n=>n.message.includes("初审通过")));assert(!JSON.stringify(notices).includes("INTERNAL-REVIEW-ONLY"));
  assert.deepEqual((await request(b,"GET","/api/me/creative/notifications")).items,[]);
  const v2={...own.content,title:"用户导航第二版",files:[{path:"Navigation.kt",content:'@Composable fun Navigation() { Text("用户原创 v2") }'}]};
  item=await request(a,"PUT",route+"/draft",{expected_version:own.row_version,content:v2});
  item=await request(a,"POST",route+"/submit",{...action(item),sharing_confirmed:true});
  assert.equal((await request(b,"GET",publicRoute)).title,published.title);
  await page.getByRole("button",{name:"刷新",exact:true}).click();
  await page.getByRole("button",{name:"查看稿件与差异",exact:true}).click();
  assert.match(await page.locator("dialog[open] .review-columns").last().innerText(),/用户原创 v1/);
  assert.match(await page.locator("dialog[open] .review-columns").last().innerText(),/用户原创 v2/);
  await page.getByLabel("作者可见的审核意见",{exact:true}).fill("请补充接入说明");
  await page.getByRole("button",{name:"退回修改",exact:true}).click();
  await page.locator("dialog[open]").waitFor({state:"hidden"});
  own=await request(a,"GET",route);assert(own.feedback.some(f=>f.feedback==="请补充接入说明"));
  assert.equal((await request(b,"GET",publicRoute)).title,published.title);
  item=await request(a,"PUT",route+"/draft",{expected_version:own.row_version,content:{...v2,integration:"接入现有导航容器"}});
  item=await request(a,"POST",route+"/submit",{...action(item),sharing_confirmed:true});
  await page.getByRole("button",{name:"刷新",exact:true}).click();
  await page.getByRole("button",{name:"查看稿件与差异",exact:true}).click();
  await request(a,"POST",route+"/withdraw",{expected_version:item.row_version,revision_id:item.revision_id});
  await page.getByRole("button",{name:"批准并发布",exact:true}).click();
  await page.waitForFunction(()=>document.querySelector("dialog[open] .form-error")?.textContent.includes("已被修改"));
  await page.screenshot({path:path.join(output,"community-stale-review.png")});
  await page.getByRole("button",{name:"关闭",exact:true}).click();
  assert.equal((await request(b,"GET",publicRoute)).title,published.title);
  own=await request(a,"GET",route);
  item=await request(a,"PUT",route+"/draft",{expected_version:own.row_version,content:{...v2,integration:"完善接入说明"}});
  item=await request(a,"POST",route+"/submit",{...action(item),sharing_confirmed:true});
  await page.getByRole("button",{name:"刷新",exact:true}).click();
  await page.getByRole("button",{name:"查看稿件与差异",exact:true}).click();
  await page.getByRole("button",{name:"批准并发布",exact:true}).click();
  await page.locator("dialog[open]").waitFor({state:"hidden"});
  assert.equal((await request(b,"GET",publicRoute)).title,"用户导航第二版");
  await request(b,"PUT",`/api/me/creative/favorites/${item.id}`,{});
  assert.deepEqual((await request(b,"GET","/api/me/creative/favorites")).creative_ids,[item.id]);
  const report=await request(b,"POST",publicRoute+"/reports",{client_id:randomUUID(),reason:"privacy",details:"示例中可能包含个人联系信息"},201);
  await page.locator('[data-admin-view="reports"]').click();await page.getByRole("button",{name:"查看并处理",exact:true}).click();
  await page.getByText("示例中可能包含个人联系信息",{exact:true}).waitFor();
  await page.getByLabel("举报人可见的处理结果",{exact:true}).fill("已核对并停止公开");
  await page.getByLabel("管理员内部备注（不向举报人或作者公开）",{exact:true}).fill("INTERNAL-REPORT-ONLY");
  await page.screenshot({path:path.join(output,"community-report.png")});
  await page.getByRole("button",{name:"处理并下架",exact:true}).click();await page.locator("dialog[open]").waitFor({state:"hidden"});
  await request(b,"GET",publicRoute,null,404);
  assert.deepEqual((await request(b,"GET","/api/me/creative/favorites")).creative_ids,[]);
  const ownReports=await request(b,"GET","/api/me/creative/reports");assert.equal(ownReports.items.find(r=>r.id===report.id).resolution,"已核对并停止公开");assert(!JSON.stringify(ownReports).includes("INTERNAL-REPORT-ONLY"));
  const authorMessages=await request(a,"GET","/api/me/creative/notifications");assert(authorMessages.items.some(n=>n.message.includes("停止公开")));assert(!JSON.stringify(authorMessages).includes("INTERNAL-REPORT-ONLY"));
  console.log("creative-community: submission/moderation, favorites, report handling/takedown, private notes, version isolation and stale-review protection passed");
};
if(require.main===module){process.env.CREATIVE_TEST_COMMUNITY="1";require("./creative-live.test.js");}
