const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',{'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream');res.end(data)});});
async function fixture(page,surface,options={}){
 await page.evaluate(({keep=false,conversation='c'})=>{
  const api=AiPanel.client,store=AiPanel.submissions;api.configure({baseUrl:location.origin,token:`synthetic-${Math.random()}`});
  window.posts=[];window.lookups=[];window.creates=[];window.watchers=[];window.watchCallbacks=new Map();window.jobList=[];window.picker=[];window.jobReads=[];
  api.askConversation=(id,body)=>new Promise((resolve,reject)=>posts.push({id,body,resolve,reject}));api.lookupTaskSubmission=(id,key)=>new Promise((resolve,reject)=>lookups.push({id,key,resolve,reject}));api.createConversation=id=>new Promise((resolve,reject)=>creates.push({id,resolve,reject}));
  api.jobs=async()=>({jobs:jobList});api.projects=async()=>({projects:[{id:'p',name:'Synthetic project'}]});api.models=async()=>({models:[]});api.conversations=async()=>({conversations:[{id:'c',project_id:'p',title:'Test'}]});api.conversationEvents=async()=>({events:[],has_more:false});api.listApprovals=async()=>({approvals:[]});api.jobMessages=async id=>({schema_version:1,job_id:id,messages:[]});api.watchJob=(id,callback)=>{watchers.push(id);watchCallbacks.set(id,callback);return{close(){}}};api.job=async id=>{jobReads.push(id);return{job:jobList.find(j=>j.id===id)}};agentDesktop.openFileDialog=()=>new Promise(resolve=>picker.push(resolve));
  if(!keep){localStorage.removeItem(TaskSubmissions.STORAGE_KEY);store.restore();store.states.clear();store.adoptions.clear();}store.foreground=true;store.bindings.clear();
  AiPanel.debug.setState({connected:true,userId:'alice',selectedProjectId:'p',conversationId:conversation,conversations:[{id:'c',project_id:'p'}],currentJobId:null,currentJob:null,running:false,jobStatus:null,contextChips:[],controlBusy:null,runMode:'workspace'});
  const cx=CodexiaAgentView._internal.getState();cx.selectedId=null;cx.selectedProjectId='p';cx.selectedConversationId=conversation;cx.busy=false;cx.contextFiles=[];cx.goal='';cx.planMode=false;cx.runMode='workspace';CodexiaAgentView._internal.setDebugData({projects:[{id:'p',name:'Synthetic project'}],jobs:[],models:[]});document.getElementById('promptInput').value='';document.getElementById('cxAgentPrompt').value='';
  window.ack=(r,index=0,status='paused')=>({schema_version:1,conversation_id:'c',submission:{schema_version:1,request_key:r.body?.request_key||r.key,project_id:'p',conversation_id:'c',job_id:`job-${index}`,turn_id:`turn-${index}`,created_at:123},job:{id:`job-${index}`,project_id:'p',conversation_id:'c',turn_id:`turn-${index}`,status,prompt:'Synthetic task <script>not HTML</script>'}});
 },options);
 if(await page.evaluate(()=>CodexiaAgentView.isVisible())) { if(surface==='cx')return; await page.locator('#cxSidebarDownload').click(); }
 await page.locator(`[data-mode="${surface==='cx'?'agent-windows':'agent'}"]`).click();
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1320,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/src/index.html?__agent_windows_fixture=1`);await page.waitForFunction(()=>window.AiPanel?.submissions&&CodexiaAgentView?._internal.getState().initialized);
 for(const surface of ['ai','cx']){
 const input=surface==='ai'?'#promptInput':'#cxAgentPrompt',send=surface==='ai'?'#btnSend':'#cxSendAgent',host=surface==='ai'?'#aiTaskSubmission':'#cxTaskSubmission';
 await fixture(page,surface);await page.locator(input).fill('original request');await page.locator(send).click();await page.locator(send).dispatchEvent('click');assert.equal(await page.evaluate(()=>posts.length),1);assert.equal(await page.locator(input).inputValue(),'original request');await page.locator(input).fill('new draft');await page.evaluate(()=>posts[0].resolve(ack(posts[0])));await page.waitForFunction(()=>!AiPanel.submissions.records.size);assert.equal(await page.locator(input).inputValue(),'new draft');assert.equal(await page.evaluate(s=>s==='ai'?AiPanel.getState().currentJobId:CodexiaAgentView._internal.getState().selectedId,surface),'job-0');
 await fixture(page,surface);await page.locator(input).fill('ABA');await page.locator(send).click();await page.locator(input).fill('B');await page.locator(input).fill('ABA');await page.evaluate(()=>posts[0].resolve(ack(posts[0])));await page.waitForFunction(()=>!AiPanel.submissions.records.size);assert.equal(await page.locator(input).inputValue(),'ABA');
 // Attachment/mode ABA is a new draft, even when text and final controls match.
 await fixture(page,surface);await page.locator(input).fill('attachment ABA');await page.locator(send).click();
 if(surface==='ai'){await page.evaluate(()=>AiPanel.addTerminalContext('p','synthetic','temporary context'));await page.locator('.composer-chip .remove').click();}
 else{for(let count=0;count<2;count++){await page.locator('#cxAttach').click();await page.locator('#cxPlanMode').click();}}
 await page.evaluate(()=>posts[0].resolve(ack(posts[0])));await page.waitForFunction(()=>!AiPanel.submissions.records.size);assert.equal(await page.locator(input).inputValue(),'attachment ABA');
 // Same-account token rotation plus a late old ACK cannot clear the pending request or a new draft.
 await fixture(page,surface);await page.locator(input).fill('token ABA');await page.locator(send).click();
 await page.evaluate(()=>{window.oldSubmission=posts[0];AiPanel.client.configure({baseUrl:location.origin,token:'replacement-token'});AiPanel.debug.setState({userId:'bob'});AiPanel.debug.setState({userId:'alice'});});
 await page.locator(input).fill('draft after login');await page.evaluate(()=>oldSubmission.resolve(ack(oldSubmission)));await page.waitForFunction(()=>!AiPanel.submissions.operations.size);assert.equal(await page.evaluate(()=>AiPanel.submissions.records.size),1);assert.equal(await page.locator(input).inputValue(),'draft after login');
 // Conversation A -> B -> A invalidates both view bindings.
 await fixture(page,surface);await page.locator(input).fill('conversation ABA');await page.locator(send).click();
 await page.evaluate(async surface=>{if(surface==='ai'){await AiPanel.selectConversation('other',{loadHistory:false});await AiPanel.selectConversation('c',{loadHistory:false});}else{const state=CodexiaAgentView._internal.getState();state.selectedConversationId='other';state.selectedConversationId='c';}},surface);
 await page.locator(input).fill('new conversation draft');await page.evaluate(()=>posts[0].resolve(ack(posts[0])));await page.waitForFunction(()=>!AiPanel.submissions.operations.size);assert.equal(await page.evaluate(()=>AiPanel.submissions.records.size),1);assert.equal(await page.locator(input).inputValue(),'new conversation draft');
 await fixture(page,surface);await page.locator(input).fill('background');await page.locator(send).click();await page.evaluate(()=>{dispatchEvent(new Event('blur'));dispatchEvent(new Event('focus'));posts[0].resolve(ack(posts[0]));});await page.waitForFunction(()=>!AiPanel.submissions.operations.size);assert.equal(await page.evaluate(()=>AiPanel.submissions.records.size),1);assert.equal(await page.locator(input).inputValue(),'background');
 await fixture(page,surface);await page.locator(input).fill('password=synthetic response loss');await page.locator(send).click();await page.evaluate(()=>posts[0].reject(new Error('response lost')));await page.waitForFunction(()=>!AiPanel.submissions.operations.size);await page.locator(host).getByRole('button',{name:'刷新关联任务',exact:true}).click();await page.evaluate(()=>lookups.at(-1).resolve(ack(lookups.at(-1))));await page.locator(host).getByText('已找到关联任务，原提交待确认',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>AiPanel.submissions.records.size),1);assert.deepEqual(await page.evaluate(()=>watchers),[]);
 await page.evaluate(()=>{jobList=[ack(lookups.at(-1)).job];CodexiaAgentView._internal.setDebugData({projects:[{id:'p',name:'P'}],jobs:jobList});});
 if(surface==='ai')await page.evaluate(()=>AiPanel.openJob('job-0'));else {await page.locator('.cx-project-task').click();await page.evaluate(()=>CodexiaAgentView.setLayout('grid'));assert.equal(await page.locator('.cx-approval-approve').count(),0);await page.evaluate(()=>CodexiaAgentView.setLayout('solo'));}
 assert.deepEqual(await page.evaluate(()=>watchers),[],'pending candidate cannot bypass original-body confirmation through task history');
 await page.locator(host).getByRole('button',{name:'查看关联任务',exact:true}).click();await page.evaluate(()=>lookups.at(-1).resolve(ack(lookups.at(-1))));await page.getByRole('dialog',{name:'关联任务详情'}).waitFor();assert.match(await page.getByRole('dialog').textContent(),/not HTML/);assert.equal(await page.locator('dialog script').count(),0);assert.deepEqual(await page.evaluate(()=>watchers),[]);await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();
 fs.mkdirSync(path.resolve(root,'../.artifacts/iteration-009'),{recursive:true});await page.screenshot({path:path.resolve(root,`../.artifacts/iteration-009/submission-${surface}.png`)});
 await page.locator(input).fill('keep newer draft');await page.locator(host).getByRole('button',{name:'核对并重试原提交'}).click();assert.deepEqual(await page.evaluate(()=>posts[1].body),await page.evaluate(()=>posts[0].body));await page.evaluate(()=>posts[1].resolve(ack(posts[1])));await page.waitForFunction(()=>!AiPanel.submissions.records.size);assert.equal(await page.locator(input).inputValue(),'keep newer draft');
 await fixture(page,surface);await page.locator(input).fill('remove uncertain');await page.locator(send).click();await page.evaluate(()=>posts[0].reject(new Error('lost')));await page.waitForFunction(()=>!AiPanel.submissions.operations.size);page.once('dialog',d=>d.accept());await page.locator(host).getByRole('button',{name:'仅移除本机记录'}).click();assert.equal(await page.evaluate(()=>AiPanel.submissions.holds.size),1);assert.equal(await page.evaluate(()=>AiPanel.submissions.records.size),0);
 await fixture(page,surface,{keep:true});await page.evaluate(()=>{jobList=[{id:'danger',project_id:'p',conversation_id:'c',turn_id:'danger-turn',status:'awaiting_approval'}];CodexiaAgentView._internal.setDebugData({projects:[{id:'p',name:'P'}],jobs:jobList});});await page.evaluate(()=>AiPanel.selectConversation('c',{loadHistory:true}));assert.deepEqual(await page.evaluate(()=>watchers),[]);assert.equal(await page.evaluate(()=>AiPanel.submissions.canAutoAttach(AiPanel.submissions.scope('p','c'))),false);
 if(surface==='cx'){await page.locator('.cx-project-task').click();await page.waitForFunction(()=>CodexiaAgentView._internal.getState().selectedId==='danger');assert.ok(await page.evaluate(()=>jobReads.includes('danger')));assert.equal(await page.evaluate(()=>AiPanel.submissions.holds.size),1);
 await page.evaluate(()=>{const s=CodexiaAgentView._internal.getState();s.selectedConversationId='other';s.selectedConversationId='c';CodexiaAgentView._internal.setDebugData({projects:[{id:'p',name:'P'}],jobs:jobList});});assert.equal(await page.evaluate(()=>CodexiaAgentView._internal.getState().selectedId),null,'an explicit hold choice authorizes only its live conversation binding');}
 await fixture(page,surface,{conversation:null});await page.locator(input).fill('before create');await page.locator(send).click();await page.locator(input).fill('after create');assert.equal(await page.evaluate(()=>creates.length),1);
 await page.evaluate(()=>{AiPanel.startAgent('other entry','p',{conversationId:null}).catch(()=>{});const mode=document.getElementById('runModeSelect');mode.value='read_only';mode.dispatchEvent(new Event('change'));CodexiaAgentView._internal.getState().runMode='read_only';});
 assert.equal(await page.evaluate(()=>creates.length),1,'shared synchronous gate precedes conversation creation');
 await page.evaluate(()=>creates[0].resolve({id:'c',project_id:'p'}));await page.waitForFunction(()=>posts.length===1);assert.match(await page.evaluate(()=>posts[0].body.prompt),/before create/);assert.equal(await page.evaluate(()=>posts[0].body.run_mode),'workspace');await page.evaluate(()=>posts[0].resolve(ack(posts[0])));await page.waitForFunction(()=>!AiPanel.submissions.records.size);assert.equal(await page.locator(input).inputValue(),'after create');
 console.log(`submission browser ${surface}: PASS`);
 }
 await fixture(page,'cx');await page.evaluate(()=>{document.getElementById('promptInput').value='AI composer untouched';AiPanel.getState().contextChips=[{kind:'selection',text:'AI secret context'}];});await page.locator('#cxAttach').click();await page.locator('#cxAddFile').click();await page.evaluate(()=>{dispatchEvent(new Event('blur'));dispatchEvent(new Event('focus'));picker[0]('/test/file.txt');});await page.waitForFunction(()=>CodexiaAgentView._internal.getState().contextFiles.length===1);await page.locator('#cxAgentPrompt').fill('CX request');await page.locator('#cxSendAgent').click();assert.match(await page.evaluate(()=>posts[0].body.prompt),/file.txt/);assert.doesNotMatch(await page.evaluate(()=>posts[0].body.prompt),/AI secret/);assert.equal(await page.locator('#promptInput').inputValue(),'AI composer untouched');await page.evaluate(()=>posts[0].resolve(ack(posts[0])));await page.waitForFunction(()=>!AiPanel.submissions.records.size);
 await fixture(page,'ai');await page.locator('#promptInput').fill('view ABA');await page.locator('#btnSend').click();await page.locator('[data-mode="agent-windows"]').click();await page.locator('#cxSidebarDownload').click();await page.locator('[data-mode="agent"]').click();await page.evaluate(()=>posts[0].resolve(ack(posts[0])));await page.waitForFunction(()=>!AiPanel.submissions.operations.size);assert.equal(await page.evaluate(()=>AiPanel.submissions.records.size),1);
 // A conversation bootstrap that began before a submission ACK cannot steal its binding.
 await fixture(page,'ai');
 await page.evaluate(()=>{window.deferredJobs=[];window.oldJob={id:'old-completed',project_id:'p',conversation_id:'c',turn_id:'old-turn',status:'succeeded'};AiPanel.client.jobs=()=>new Promise(resolve=>deferredJobs.push(resolve));window.selectionTask=AiPanel.selectConversation('c',{loadHistory:true});});
 await page.waitForFunction(()=>deferredJobs.length===1);await page.evaluate(()=>deferredJobs[0]({jobs:[oldJob]}));await page.waitForFunction(()=>deferredJobs.length===2);
 await page.locator('#promptInput').fill('new task while prior list is delayed');await page.locator('#btnSend').click();await page.evaluate(()=>posts[0].resolve(ack(posts[0],0,'awaiting_approval')));await page.waitForFunction(()=>AiPanel.getState().currentJobId==='job-0');
 await page.evaluate(async()=>{deferredJobs[1]({jobs:[oldJob]});await selectionTask;});
 assert.equal(await page.evaluate(()=>AiPanel.getState().currentJobId),'job-0');assert.equal(await page.evaluate(()=>AiPanel.getState().running),true);
 // The same bootstrap still adopts the newest task when no newer binding exists.
 await fixture(page,'ai');await page.evaluate(async()=>{jobList=[{id:'restore-job',project_id:'p',conversation_id:'c',turn_id:'restore-turn',status:'awaiting_approval'}];await AiPanel.selectConversation('c',{loadHistory:true});});assert.equal(await page.evaluate(()=>AiPanel.getState().currentJobId),'restore-job');
 // Canonical prompt can arrive before task-only status events. They must stay
 // in the acknowledged turn, keeping its resolved approval visible on completion.
 await fixture(page,'ai');await page.evaluate(()=>{AiPanel.debug.timeline.reset();AiPanel.debug.renderTimeline();AiPanel.client.conversationEvents=async()=>({events:[{seq:900,event_type:'user_message',task_id:'job-0',turn_id:'turn-0',created_at:1,payload:{message_id:'prompt-0',content:'canonical prompt'}}]});});
 await page.locator('#promptInput').fill('canonical prompt');await page.locator('#btnSend').click();await page.evaluate(()=>posts[0].resolve(ack(posts[0],0,'awaiting_approval')));await page.waitForFunction(()=>AiPanel.debug.timeline.items().some(item=>item.messageId==='prompt-0'));
 await page.evaluate(async()=>{const callback=watchCallbacks.get('job-0');for(const event of [
  {id:901,type:'session',message:'existing turn context'},
  {id:902,type:'status',message:'working'},
  {id:903,type:'tool_call',tool_call_id:'command-call',name:'run_command',input:{argv:['synthetic']}},
  {id:904,type:'approval_required',approval_id:'command-approval',tool_call_id:'command-call',kind:'process'},
  {id:905,type:'approval_resolved',approval_id:'command-approval',decision:'approved'},
  {id:906,type:'tool_result',tool_call_id:'command-call',name:'run_command',ok:true},
  {id:907,type:'completed'},
 ])await callback({kind:'event',event});jobList=[{...ack(posts[0],0,'succeeded').job,events:[{id:908,type:'status',message:'late completion diagnostic'}]}];await callback({kind:'done',status:'succeeded'});});
 await page.waitForFunction(()=>AiPanel.getState().jobStatus==='succeeded');await page.evaluate(()=>AiPanel.debug.ingestConversationEvents([{seq:909,event_type:'turn_started',task_id:'job-0',turn_id:'turn-0',created_at:1,payload:{}}]));await page.locator('#aiMessages .tl-turn.is-succeeded').first().waitFor();
 assert.equal(await page.locator('#aiMessages .tl-turn').count(),1,'task-only statuses must not create a phantom newest turn');assert.equal(await page.locator('#aiMessages [data-approval-id="command-approval"].is-approved').count(),1);
 assert.ok(await page.evaluate(()=>AiPanel.debug.timeline.items().every(item=>item.turnId==='turn-0')),'live and completion fallback both carry the known turn identity');
 // AgentView already fences stale list reads with dataEpoch in mergeJob.
 await fixture(page,'cx');await page.locator('#cxAgentPrompt').fill('CX accepted during older refresh');await page.locator('#cxSendAgent').click();await page.evaluate(()=>{window.cxDeferred=[];const state=CodexiaAgentView._internal.getState();state.debugData=null;AiPanel.client.jobs=()=>new Promise(resolve=>cxDeferred.push(resolve));window.cxRefresh=CodexiaAgentView.refresh({quiet:true});});await page.waitForFunction(()=>cxDeferred.length===1);
 // A pending POST may settle while a background list refresh is in flight.
 await page.evaluate(()=>posts[0].resolve(ack(posts[0],0,'awaiting_approval')));await page.waitForFunction(()=>CodexiaAgentView._internal.getState().selectedId==='job-0');await page.evaluate(async()=>{cxDeferred[0]({jobs:[{id:'old-completed',project_id:'p',conversation_id:'c',turn_id:'old-turn',status:'succeeded'}]});await cxRefresh;});assert.equal(await page.evaluate(()=>CodexiaAgentView._internal.getState().selectedId),'job-0');
 console.log('submission binding regressions: PASS (stale bootstrap, normal restore, canonical-first statuses, CX stale refresh)');
 assert.deepEqual(errors,[]);console.log('task-submissions-browser.test: OK (both entries, draft/visibility ABA, lost response, candidate only, retry, hold, create race, attachments)');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
