#!/usr/bin/env python3
"""Generate the catalog and copyable code from the exact native preview implementations.

Run after editing tools/creative/catalog.json or creative/styles/Style*.kt.
--check is read-only and fails if committed generated files are stale.
The optional Gradle validation script exports the actual runtime-generated recipes.
"""
import argparse
import json
import re
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'android-app/app/src/main/java/com/androidagent/client/creative/styles'
DATA = ROOT / 'tools/creative/catalog.json'


def quote(value):
    return json.dumps(value, ensure_ascii=False).replace('$', r'\$')


def kotlin_list(values):
    return 'listOf(' + ', '.join(quote(v) for v in values) + ')'


def style_literal(s):
    values = [quote(s['id']), quote(s['label'])]
    values += ['0xFF' + s[key] for key in ['background', 'surface', 'ink', 'accent', 'secondary']]
    values += [str(s['radius']), str(s['border']), quote(s['finish']), quote(s['typography'])]
    return 'CreativeStyleSpec(' + ', '.join(values) + ')'


def pattern_literal(p):
    values = [quote(p[k]) for k in ['id', 'title', 'headline', 'caption', 'value', 'action']]
    return 'CreativePattern(' + ', '.join(values + [kotlin_list(p['items'])]) + ')'


def load():
    data = json.loads(DATA.read_text())
    style_ids = [s['id'] for s in data['styles']]
    pattern_ids = [p['id'] for p in data['patterns']]
    assert len(style_ids) == len(set(style_ids)), 'Duplicate style ids'
    assert len(pattern_ids) == len(set(pattern_ids)), 'Duplicate layout ids'
    legacy = (DEST.parent / 'CreativeCatalog.kt').read_text()
    legacy_count = len(re.findall(r'id = "[a-z0-9-]+"', legacy))
    count = legacy_count
    for s in data['styles']:
        assert re.fullmatch('[a-z][a-z0-9-]*', s['id']), s['id']
        assert len(s['patterns']) == len(set(s['patterns'])), s['id']
        assert set(s['patterns']) <= set(pattern_ids), s['id']
        for key in ['background', 'surface', 'ink', 'accent', 'secondary']:
            assert re.fullmatch('[0-9A-F]{6}', s[key]), (s['id'], key)
        count += len(s['patterns'])
        for ref in [s['reference'], data['patternReference']]:
            parsed = urlparse(ref['url'])
            assert parsed.scheme == 'https' and parsed.netloc and not parsed.username, ref
    assert count <= min(data['limit'], 500), f'Catalog exceeds 500: {count}'
    for p in data['patterns']:
        assert len(p['items']) == 3 and all(p['items']), p['id']
    foundation = (DEST / 'StyleFoundation.kt').read_text().split('\n', 1)[1].lstrip()
    foundation = foundation.replace('internal ', 'private ').replace('data class ', 'private data class ')
    layout_file = (DEST / 'StyleLayouts.kt').read_text()
    layouts = {}
    for chunk in layout_file.split('// pattern:')[1:]:
        key, body = chunk.split('\n', 1)
        body = body.strip().replace('internal ', 'private ')
        name = re.search(r'fun (Style\w+)\(', body).group(1)
        layouts[key.strip()] = (name, body)
    assert set(layouts) == set(pattern_ids), 'Native layout/catalog mismatch'
    return data, foundation, layouts, count


def generate(data, foundation, layouts):
    header = '// Generated by scripts/generate_creative_catalog.py. Do not edit.\n'
    package = 'package com.androidagent.client.creative.styles\n\n'
    lines = [header + package, 'import com.androidagent.client.creative.*\n', 'internal object CreativeStyleCatalog {']
    lines += ['    val styles = listOf('] + ['        ' + style_literal(s) + ',' for s in data['styles']] + ['    )']
    lines += ['    val patterns = listOf('] + ['        ' + pattern_literal(p) + ',' for p in data['patterns']] + ['    ).associateBy { it.id }']
    for name, values in [
        ('selections', [(s['id'], kotlin_list(s['patterns'])) for s in data['styles']]),
        ('styleSummaries', [(s['id'], quote(s['summary'])) for s in data['styles']]),
        ('patternSummaries', [(p['id'], quote(p['summary'])) for p in data['patterns']]),
        ('categories', [(p['id'], 'CreativeCategory.' + p['category']) for p in data['patterns']]),
        ('references', [(s['id'], 'CreativeReference(' + quote(s['reference']['title']) + ', ' + quote(s['reference']['url']) + ')') for s in data['styles']]),
    ]:
        lines += [f'    private val {name} = mapOf('] + [f'        {quote(k)} to {v},' for k, v in values] + ['    )']
    ref = data['patternReference']
    lines += [f'    private val patternReference = CreativeReference({quote(ref["title"])}, {quote(ref["url"])})']
    lines += ['''
    val recipes: List<CreativeRecipe> = (0 until selections.values.maxOf { it.size }).flatMap { index ->
        styles.mapNotNull { style ->
            selections.getValue(style.id).getOrNull(index)?.let { patternId ->
                val pattern = patterns.getValue(patternId)
                val id = "${style.id}-${pattern.id}"
                val refs = listOf(references.getValue(style.id), patternReference)
                CreativeRecipe(
                    id = id,
                    title = "${style.label} · ${pattern.title}",
                    summary = "${styleSummaries.getValue(style.id)}。${patternSummaries.getValue(pattern.id)}。",
                    category = categories.getValue(patternId),
                    preview = CreativePreview.STYLE,
                    tags = linkedSetOf(style.label, pattern.title, style.id, pattern.id, categories.getValue(patternId).label),
                    style = style,
                    pattern = pattern,
                    references = refs,
                    sourceBuilder = { CreativeStyleSources.build(style, pattern, refs.map { it.url }) },
                )
            }
        }
    }
}''']
    catalog = '\n'.join(lines) + '\n'
    dispatcher = header + package + '''import androidx.compose.runtime.Composable

@Composable
internal fun CreativeStyleContent(style: CreativeStyleSpec, pattern: CreativePattern, interactive: Boolean) {
    when (pattern.id) {
'''
    for key, (name, _) in layouts.items():
        dispatcher += f'        {quote(key)} -> {name}(style, pattern, interactive)\n'
    dispatcher += '        else -> error("Unknown creative layout: ${pattern.id}")\n    }\n}\n'
    sources = [header + package, 'internal object CreativeStyleSources {', '    private const val foundation = ' + quote(foundation)]
    helpers = re.findall(r'(?:data class|fun) (\w+)\(', foundation)
    sources += ['    private val sharedHelpers = ' + kotlin_list(helpers)]
    sources += ['    private val layouts = mapOf('] + [f'        {quote(key)} to {quote(body)},' for key, (_, body) in layouts.items()] + ['    )']
    sources += ['    private val names = mapOf('] + [f'        {quote(key)} to {quote(name)},' for key, (name, _) in layouts.items()] + ['    )']
    sources += [r'''
    private fun quoted(value: String): String = "\"" + value.replace("\\", "\\\\")
        .replace("\"", "\\\"").replace("$", "\\$").replace("\n", "\\n") + "\""

    fun build(s: CreativeStyleSpec, p: CreativePattern, references: List<String>): String {
        val styleArgs = listOf(quoted(s.id), quoted(s.label)) +
            listOf(s.background, s.surface, s.ink, s.accent, s.secondary).map { "0x" + it.toString(16).uppercase() } +
            listOf(s.radius.toString(), s.border.toString(), quoted(s.finish), quoted(s.typography))
        val patternArgs = listOf(p.id, p.title, p.headline, p.caption, p.value, p.action).map(::quoted) +
            "listOf(${p.items.joinToString(", ", transform = ::quoted)})"
        val entry = "Creative" + "${s.id}-${p.id}".split('-').joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }
        return buildString {
            appendLine("// ${s.label} · ${p.title}")
            appendLine("// 原创 Compose 演示；复制到已启用 Compose Material3 的 Kotlin 文件。最低 SDK 24。")
            appendLine("// 用法：$entry()；示例数据与交互不连接真实业务服务。")
            references.forEach { appendLine("// 设计参考：$it") }
            appendLine(foundation)
            appendLine(layouts.getValue(p.id))
            appendLine("\n@Composable")
            appendLine("fun $entry(modifier: Modifier = Modifier) {")
            appendLine("    val style = CreativeStyleSpec(${styleArgs.joinToString(", ")})")
            appendLine("    val pattern = CreativePattern(${patternArgs.joinToString(", ")})")
            appendLine("    Box(modifier) { ${names.getValue(p.id)}(style, pattern, interactive = true) }")
            appendLine("}")
        }.let { code ->
            // Distinct helper names let independently copied recipes share a package.
            val identifiers = sharedHelpers + names.getValue(p.id)
            code.replace(Regex("\\b(" + identifiers.joinToString("|") + ")\\b")) { match -> entry + match.value }
        }
    }
}''']
    return {'CreativeStyleCatalog.kt': catalog, 'CreativeStyleDispatcher.kt': dispatcher, 'CreativeStyleSources.kt': '\n'.join(sources) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data, foundation, layouts, count = load()
    outputs = generate(data, foundation, layouts)
    for name, content in outputs.items():
        path = DEST / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'Stale generated file: {path.relative_to(ROOT)}')
        else:
            path.write_text(content)
    print(f'Creative catalog: {count}/{data["limit"]} recipes; {len(data["styles"])} styles; {len(layouts)} native layouts; generated sources {"verified" if args.check else "updated"}.')


if __name__ == '__main__':
    main()
